<a href="https://colab.research.google.com/github/tomcat472/ML_on_GIS/blob/main/matrics_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# array comparisons
a=np.array([1,2,3,4])
b=np.array([2,2,4,4])
a==b

array([False,  True, False,  True])

In [3]:
a != b

array([ True, False,  True, False])

In [4]:
# matrices 
A=np.array([[1,2],[3,4]])
# 2x2 matrices
print(A)

[[1 2]
 [3 4]]


In [5]:
B=np.array([[1,0],[0,1]])
print(B)

[[1 0]
 [0 1]]


In [6]:
A-B

array([[0, 2],
       [3, 3]])

In [7]:
C=np.array([[1,0],[0,1]])
print(C*-2)

[[-2  0]
 [ 0 -2]]


In [8]:
# y=Xb
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,4,6])
y=X @ b
print(y)
# mxn matrics ကိုမြှောက်မယ်ဆိုရင် nxm ရှိဖို့တော့လိုပါတယ်။

[27 60 93]


In [10]:
X=np.array([[1,2],[4,5]])
b=np.array([[1,4],[2,4]])
X@b

array([[ 5, 12],
       [14, 36]])

In [16]:
X=np.array([[4,5],[2,4],[3,4]])
B=np.array([[3,-2],[-2,5]])
X@B

array([[ 2, 17],
       [-2, 16],
       [ 1, 14]])

In [17]:
y=X@B
y.T

array([[ 2, -2,  1],
       [17, 16, 14]])

In [18]:
y.transpose()

array([[ 2, -2,  1],
       [17, 16, 14]])

In [23]:
# inverse matrics
x=np.array([[1,1],[42,3]])
np.linalg.inv(x)

array([[-0.07692308,  0.02564103],
       [ 1.07692308, -0.02564103]])

In [25]:
A=np.array([[1,2,3],[2,3,6],[7,11,13]])
np.linalg.inv(A)

array([[-3.375,  0.875,  0.375],
       [ 2.   , -1.   ,  0.   ],
       [ 0.125,  0.375, -0.125]])

In [26]:
# Vectorization
a=np.array([1,2,3])
print(a,a.shape)

[1 2 3] (3,)


In [27]:
A=np.array([[1,2,3,3],[4,5,6,5],[7,8,9,10]])
A

array([[ 1,  2,  3,  3],
       [ 4,  5,  6,  5],
       [ 7,  8,  9, 10]])

In [30]:
A.reshape(3,4)

array([[ 1,  2,  3,  3],
       [ 4,  5,  6,  5],
       [ 7,  8,  9, 10]])